[package]
name = "GMTK_GJ_22"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
blit = "0.5"
qoi = "0.4.0"
gilrs = "0.8.2"